---
abstract: Low-level access to Win32 system API calls for files/dirs.
author:
  - 'Tye McQueen <tye@metronet.com>'
build_requires:
  File::Spec: 0
  IO::File: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.571, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Win32API-File
no_index:
  directory:
    - t
    - inc
requires:
  Math::BigInt: 0
  Win32: 0
  perl: 5.001
resources:
  repository: http://github.com/chorny/Win32API-File
version: 0.1200
